### ISSUE TITLE
GLSurface剥离原父布局重新绑定新父布局会导致GLSurface渲染失效。

### ISSUE THREAD

**Issue by hellojuly** [AgoraIO/FaceUnityLegacy#12]
连麦场景时，参考OpenLive Demo，进行GLSurfaceView的父布局重新绑定。此Demo中的GLSurface会停止渲染，使用sdk的GLSurfaceView则无此问题。

**Comment by brianxcli** [comment]
现在直接使用 FaceUnity 自己的 GLRenderer 来进行渲染。其中嵌套了 gl 的初始化过程。如果模仿 OpenLive 的写法，会导致 gl 线程状态错误。推荐您自己实现一个 gl 自渲染的逻辑。

**Comment by guohai** [comment]
@hellojuly 没有后续反馈，关闭此 issue
