### ISSUE TITLE
切换channel 的问题

### ISSUE THREAD

**Issue by ghost** [AgoraIO/FaceUnityLegacy#39]
中途切换channel，另一部手机加入新的channel 只会受到onUserJoin的回调，并没有回调onFirstRemoteVideoDecoded，该怎么处理啊

**Comment by plutoless** [comment]
是用switchChannel切换吗？

**Comment by ghost** [comment]
> 是用switchChannel切换吗？
不是，用的leave 和 join,后来释放了资源重新创建解决了这个问题， 不知道什么原因
