### ISSUE TITLE
iOS have error,How to fix it?

### ISSUE THREAD

**Issue by ninenox** [AgoraIO/FaceUnityLegacy#42]
<img width="1315" alt="Screen Shot 2563-03-03 at 12 56 41" src="https://user-images.githubusercontent.com/11360945/75748758-cf02f380-5d52-11ea-9363-6df71408588b.png">

**Comment by ShengQiangLiu** [comment]
fix this bug by “https://github.com/AgoraIO/FaceUnity/pull/43”
