### ISSUE TITLE
error bitcode AGMBase .framework on archieve xcode.

### ISSUE THREAD

**Issue by ninenox** [AgoraIO/FaceUnityLegacy#45]
<img width="1282" alt="Screen Shot 2563-03-05 at 06 37 48" src="https://user-images.githubusercontent.com/11360945/75933683-2a48f900-5ead-11ea-85d8-df2bd596945c.png">
How to fix it?

**Comment by plutoless** [comment]
looks like you have a third party dependency which does not enable bitcode

**Comment by ninenox** [comment]
AGMBase.framework support bitcode?

**Comment by plutoless** [comment]
looks like so. the console tells AGMBase.framework is not built with full bitcode.

**Comment by ninenox** [comment]
How to fix it?

**Comment by plutoless** [comment]
i'll do a quick confirm with my colleague. 1 sec

**Comment by plutoless** [comment]
@nisi
sorry AGMBase is our capturing module and it was not built with bitcode enabled. you may turn off the project bitcode to unblock yourself for now, we are building an AGMBase framework with bitcode supported

**Comment by plutoless** [comment]
it will be updated today as soon as we get one.

**Comment by ninenox** [comment]
Thanks, I will wait your update and please check with AGMCapturer and AGMRenderer.

**Comment by ShengQiangLiu** [comment]
I checked and confirmed that it supports bitcode.

$ otool -arch arm64 -l AGMBase.framework/AGMBase | grep __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
  sectname __bitcode
.....

**Comment by ShengQiangLiu** [comment]
I will update this issue in the next few days.

**Comment by ShengQiangLiu** [comment]
I have updated the bitcode support, please try again.

[AgoraModule_Base_iOS-1.1.1](https://download.agora.io/components/release/AgoraModule_Base_iOS-1.1.1.zip)
[AgoraModule_Capturer_iOS-1.1.1](https://download.agora.io/components/release/AgoraModule_Capturer_iOS-1.1.1.zip)

**Comment by ninenox** [comment]
ok, please for AGMRenderer.framework. Thanks.

**Comment by ShengQiangLiu** [comment]
[AgoraModule_Renderer_iOS-1.1.1](https://download.agora.io/components/release/AgoraModule_Renderer_iOS-1.1.1.zip)

**Comment by ninenox** [comment]
very nice! It's success.
